/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TosRouteImport } from './routes/tos'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as AuthFailedRouteImport } from './routes/_auth.failed'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppNewRouteImport } from './routes/_app.new'
import { Route as AppMessageRouteImport } from './routes/_app.message'
import { Route as AppItemIdRouteImport } from './routes/_app.$itemId'
import { Route as AppMessageMessageIdRouteImport } from './routes/_app.message.$messageId'
import { Route as AppItemIdEditRouteImport } from './routes/_app.$itemId.edit'

const TosRoute = TosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFailedRoute = AuthFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppMessageRoute = AppMessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => AppRoute,
} as any)
const AppItemIdRoute = AppItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AppRoute,
} as any)
const AppMessageMessageIdRoute = AppMessageMessageIdRouteImport.update({
  id: '/$messageId',
  path: '/$messageId',
  getParentRoute: () => AppMessageRoute,
} as any)
const AppItemIdEditRoute = AppItemIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppItemIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/tos': typeof TosRoute
  '/$itemId': typeof AppItemIdRouteWithChildren
  '/message': typeof AppMessageRouteWithChildren
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRoute
  '/failed': typeof AuthFailedRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/$itemId/edit': typeof AppItemIdEditRoute
  '/message/$messageId': typeof AppMessageMessageIdRoute
}
export interface FileRoutesByTo {
  '/tos': typeof TosRoute
  '/$itemId': typeof AppItemIdRouteWithChildren
  '/message': typeof AppMessageRouteWithChildren
  '/new': typeof AppNewRoute
  '/settings': typeof AppSettingsRoute
  '/failed': typeof AuthFailedRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/': typeof AppIndexRoute
  '/$itemId/edit': typeof AppItemIdEditRoute
  '/message/$messageId': typeof AppMessageMessageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/tos': typeof TosRoute
  '/_app/$itemId': typeof AppItemIdRouteWithChildren
  '/_app/message': typeof AppMessageRouteWithChildren
  '/_app/new': typeof AppNewRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_auth/failed': typeof AuthFailedRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$itemId/edit': typeof AppItemIdEditRoute
  '/_app/message/$messageId': typeof AppMessageMessageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/tos'
    | '/$itemId'
    | '/message'
    | '/new'
    | '/settings'
    | '/failed'
    | '/login'
    | '/signup'
    | '/'
    | '/$itemId/edit'
    | '/message/$messageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/tos'
    | '/$itemId'
    | '/message'
    | '/new'
    | '/settings'
    | '/failed'
    | '/login'
    | '/signup'
    | '/'
    | '/$itemId/edit'
    | '/message/$messageId'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/tos'
    | '/_app/$itemId'
    | '/_app/message'
    | '/_app/new'
    | '/_app/settings'
    | '/_auth/failed'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/'
    | '/_app/$itemId/edit'
    | '/_app/message/$messageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  TosRoute: typeof TosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/failed': {
      id: '/_auth/failed'
      path: '/failed'
      fullPath: '/failed'
      preLoaderRoute: typeof AuthFailedRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/new': {
      id: '/_app/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/message': {
      id: '/_app/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof AppMessageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$itemId': {
      id: '/_app/$itemId'
      path: '/$itemId'
      fullPath: '/$itemId'
      preLoaderRoute: typeof AppItemIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/message/$messageId': {
      id: '/_app/message/$messageId'
      path: '/$messageId'
      fullPath: '/message/$messageId'
      preLoaderRoute: typeof AppMessageMessageIdRouteImport
      parentRoute: typeof AppMessageRoute
    }
    '/_app/$itemId/edit': {
      id: '/_app/$itemId/edit'
      path: '/edit'
      fullPath: '/$itemId/edit'
      preLoaderRoute: typeof AppItemIdEditRouteImport
      parentRoute: typeof AppItemIdRoute
    }
  }
}

interface AppItemIdRouteChildren {
  AppItemIdEditRoute: typeof AppItemIdEditRoute
}

const AppItemIdRouteChildren: AppItemIdRouteChildren = {
  AppItemIdEditRoute: AppItemIdEditRoute,
}

const AppItemIdRouteWithChildren = AppItemIdRoute._addFileChildren(
  AppItemIdRouteChildren,
)

interface AppMessageRouteChildren {
  AppMessageMessageIdRoute: typeof AppMessageMessageIdRoute
}

const AppMessageRouteChildren: AppMessageRouteChildren = {
  AppMessageMessageIdRoute: AppMessageMessageIdRoute,
}

const AppMessageRouteWithChildren = AppMessageRoute._addFileChildren(
  AppMessageRouteChildren,
)

interface AppRouteChildren {
  AppItemIdRoute: typeof AppItemIdRouteWithChildren
  AppMessageRoute: typeof AppMessageRouteWithChildren
  AppNewRoute: typeof AppNewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppItemIdRoute: AppItemIdRouteWithChildren,
  AppMessageRoute: AppMessageRouteWithChildren,
  AppNewRoute: AppNewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthFailedRoute: typeof AuthFailedRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFailedRoute: AuthFailedRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  TosRoute: TosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
